application: payam-crm
runtime: php55
threadsafe: false

handlers:
- url: .*
  script: index.php

- url: /assets/js/*
  static_dir: assets/js

- url: /assets/css/*
  static_dir: assets/css

- url: /assets/images/*
  static_dir: images
