#application: payam-crm
runtime: php55
threadsafe: false

handlers:
- url: /assets/(.*\.(htm$|html$|css$|js$|png$|gif$|jpg$|woff2$|woff$|ttf$))
  static_files: assets/\1
  upload: assets/(.*\.(htm$|html$|css$|js$|png$))
  application_readable: true
  
- url: /favicon\.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon\.ico
  
- url: .*
  script: index.php
