#application: payam-crm
runtime: php55
threadsafe: false

handlers:
- url: /assets/(.*\.(htm$|html$|css$|js$|png$))
  static_files: assets/\1
  upload: assets/(.*\.(htm$|html$|css$|js$|png$))
  application_readable: true
  
 - url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: assets/(.+\.(gif|png|jpg)$)
  application_readable: true
  
- url: /favicon\.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon\.ico

- url: .*
  script: index.php
